### ISSUE TITLE
ship1 mapmodel

### ISSUE THREAD

**Issue by Goldenbrain1** [GrayTophatclan-GTC/mapmodels#1]
Here i began some fighter mapmodel on blender but i think it would be better with some animations like firing. Could someone help me on that ?
I tried to make some reactor animation but ull see its quite buggy (3rd layer i think or something like that)
The particles dont seem to have the shape and color i want and they appear far of the reactors
![ship1](https://user-images.githubusercontent.com/35398459/43391709-b9566084-93f1-11e8-9795-d13b85946e78.png)
[ship1.zip](https://github.com/GrayTophatclan-GTC/mapmodels/files/2240693/ship1.zip)

EDIT : I suggest we fix that working by group on discord, those of you who have discord should have received an invitation to the the GTC discord server

**Comment by FabioOG** [comment]
I finished my ship adding some under reactors and a adding reactors particles, gonna pull request

**Comment by FabioOG** [comment]
[ship1.zip](https://github.com/GrayTophatclan-GTC/mapmodels/files/2332598/ship1.zip)
